
/*What is the total revenue generated by male vs. female customers?*/

Select
	gender, SUM(purchase_amount) as revenue
FROM 
	customer_shopping
group by
	gender 
    
/*Which customers used a discount but still spent more than the average purchase amount?*/

Select 
	customer_id, purchase_amount 
From 
	customer_shopping
Where 
	discount_applied = 'Yes' AND purchase_amount >= (select avg(purchase_amount) from customer_shopping)
    
/*Which are the top 5 products with the highest average review rating?*/

Select 
	item_purchased, Round(avg(review_rating),2) 
From 	
	customer_shopping
group by
	item_purchased
Order By 
	Round(avg(review_rating),2)  DESC 
Limit 
	5
    
/*Compare the average Purchase Amounts between Standard and Express Shipping*/

Select 
	shipping_type ,avg(purchase_amount) 
from 
	customer_shopping
where 
	shipping_type in ('Standard', 'Express')
group by
	shipping_type
    
/*Do subscribed customers spend more? Compare average spend and total revenue 
between subscribers and non-subscribers*/

Select 
	Count(customer_id) as total_customer, subscription_status, avg(purchase_amount) as avg_spend, sum(purchase_amount) as total_revenue 
From 
	customer_shopping
group by
	subscription_status
Order By 
	total_customer Desc
    
/*Which 5 products have the highest percentage of purchases with discounts applied?*/

Select 
	item_purchased, Round(count(Case when discount_applied = 'Yes' then 1 End)* 100/ count(purchase_amount),2) as percentage_purchase
From 	
	customer_shopping
Group by 
	item_purchased
Order by 
	percentage_purchase Desc 
Limit 
	5

/*Segment customers into New, Returning, and Loyal based on their total 
number of previous purchases, and show the count of each segment.*/

With customer_segregation as (
Select 
	customer_id, previous_purchases, 
	Case 
		when previous_purchases = 1 Then 'New'
        when previous_purchases between 1 and 10 Then 'Returning'
        Else 'Loyal' End as customer_seg
From 	
	customer_shopping)

Select 
	customer_seg, count(*) as total_customers 
From 
	customer_segregation
Group by 
	customer_seg
    
/*What are the top 3 most purchased products within each category?*/

With item_count as (
Select
	item_purchased, 
    category, 
    count(customer_id) as total_purchase, 
    row_number() over (partition by category order by count(customer_id) desc) as item_rank
From 	
	customer_shopping
Group by 
	category, item_purchased)

Select 	
	item_purchased, category, item_rank
From 	
	item_count
Where 
	item_rank <= 3
    
/*Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?*/

Select 
	subscription_status, 
	count(customer_id) as total_buyers
From	 
	customer_shopping
Where
	previous_purchases > 5 
Group By 
	subscription_status

/*What is the revenue contribution of each age group?*/


with age_group as (
Select 
	age, 
Case 
	When age between 20 and 30 Then '20-30'
    When age between 31 and 40 Then '31-40'
    Else '>40' end as age_seg
From 
	customer_shopping
Group by 
	age_seg)
    
Select 
	age_seg
From 
	age_group
group by 
	age_seg